mod artwork;
pub mod collections;
pub mod controls;
mod empty;
mod library;
mod queue;
mod spectrum;
mod timeline;
mod track_info;
mod vu_meters;

pub use artwork::ArtworkPane;
pub use collections::{CollectionsMessage, CollectionsPane};
pub use controls::{ControlsMessage, ControlsPane};
pub use empty::EmptyPane;
pub use library::LibraryPane;
pub use queue::QueuePane;
pub use spectrum::SpectrumPane;
pub use timeline::TimelinePane;
pub use track_info::TrackInfoPane;
pub use vu_meters::VUMetersPane;
